title: Nathan Wiegand
description: Ramblings
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

    #remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Posts

collections:
  pages:
    output: true
    permalink: /pages/:name.html
rss: rss

