remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
theme: minima
title: Nathan Wiegand
description: Ramblings
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
